### PR TITLE
Rename hook to ensure it is executed after zz-snap-pac-post.hook

### PR DESCRIPTION
**Pull request by leonkacowicz**
I noticed that the snap-pac-post hook was being executed after snap-pac-grub-post, which generated a weird situation, where the snapshots and grub options were always off by one. The reason is that the hooks are executed in lexicographical order. So just adding an extra "z" in the beginning of the filename fixes the problem.

### CODE REVIEW

**Comment by max-baz** [comment]
Thanks! I just spotted #4 and am not sure what is the correct order, as it seems the current order was made on purpose, and I just can't recall all the details... Could you have a look at that thread too, please?

@ckotte if you still use this project, may I ask you to give your feedback here? 🙏

**Comment by leonkacowicz** [comment]
> Thanks! I just spotted #4 and am not sure what is the correct order, as it seems the current order was made on purpose, and I just can't recall all the details... Could you have a look at that thread too, please?
> 
> @ckotte if you still use this project, may I ask you to give your feedback here? 🙏

Yes, I read that thread. But if I'm not missing anything, it makes most sense if the grub entries are created _after_ the snapshots, otherwise my grub menu will always have an invalid entry (the oldest one that is already deleted) and will be missing the most recent entry.

**Comment by ckotte** [comment]
@maximbaz I'm using this order, but I didn't check if it still works properly. Was working 2-3 years ago..

Important pacman hooks need to be executed in a specific order:

|Type|File|Description|
|---|---|---|
|Pre|00-prevent-interruption-pre.hook|Disable power management|
|Pre|05-etckeeper-pre-install.hook|Commit changes in /etc|
|Pre|05-snap-pac-a-pre-config-sys.hook|Configure system before snapper pre snapshots|
|Pre|05-snap-pac-pre.hook|Perform snapper pre snapshots|
|xxx|xxx|xxx|
|Post|zz-snap-pac-post.hook|Perform snapper post snapshots|
|Post|zz-snap-pac-postz-config-sys.hook|Configure system after snapper post snapshots|
|Post|zz_snap-pac-grub-post.hook|Generate GRUB config|
|Post|zzz-etckeeper-post-install.hook|Commit changes in /etc|
|Post|zzz-prevent-interruption-post.hook|Enable power management|

I didn't update recently. The order on my system was right during the last update:

````
294580 [2024-06-09T05:54:41+0700] [ALPM] running 'zz-snap-pac-post.hook'...
294581 [2024-06-09T05:54:42+0700] [ALPM-SCRIPTLET] ==> root: 8530
294582 [2024-06-09T05:54:42+0700] [ALPM-SCRIPTLET] ==> var-log: 8530
294583 [2024-06-09T05:54:43+0700] [ALPM-SCRIPTLET] ==> home: 8530
294584 [2024-06-09T05:54:43+0700] [ALPM] running 'zz-snap-pac-postz-config-sys.hook'...
294585 [2024-06-09T05:54:43+0700] [ALPM-SCRIPTLET] ==> enable snapper-timeline.timer
294586 [2024-06-09T05:54:44+0700] [ALPM-SCRIPTLET] ==> enable snapper-cleanup.timer
294587 [2024-06-09T05:54:44+0700] [ALPM-SCRIPTLET] ==> enable btrbk-hourly.timer
294588 [2024-06-09T05:54:45+0700] [ALPM-SCRIPTLET] ==> enable btrbk-daily.timer
294589 [2024-06-09T05:54:45+0700] [ALPM-SCRIPTLET] ==> enable grub-btrfs
294590 [2024-06-09T05:54:45+0700] [ALPM] running 'zz_snap-pac-grub-post.hook'...
294591 [2024-06-09T05:54:45+0700] [ALPM-SCRIPTLET] Generating grub configuration file ...
294592 [2024-06-09T05:54:46+0700] [ALPM-SCRIPTLET] Found linux image: /boot/vmlinuz-linux-lts
294593 [2024-06-09T05:54:46+0700] [ALPM-SCRIPTLET] Found initrd image: /boot/intel-ucode.img /boot/initramfs-linux-lts.img
294594 [2024-06-09T05:54:47+0700] [ALPM-SCRIPTLET] Found fallback initrd image(s) in /boot:  intel-ucode.img initramfs-linux-lts-fallback.img
294595 [2024-06-09T05:54:47+0700] [ALPM-SCRIPTLET] Found linux image: /boot/vmlinuz-linux
294596 [2024-06-09T05:54:47+0700] [ALPM-SCRIPTLET] Found initrd image: /boot/intel-ucode.img /boot/initramfs-linux.img
294597 [2024-06-09T05:54:47+0700] [ALPM-SCRIPTLET] Found fallback initrd image(s) in /boot:  intel-ucode.img initramfs-linux-fallback.img
294598 [2024-06-09T05:54:47+0700] [ALPM-SCRIPTLET] Warning: os-prober will not be executed to detect other bootable partitions.
294599 [2024-06-09T05:54:47+0700] [ALPM-SCRIPTLET] Systems on them will not be added to the GRUB boot configuration.
294600 [2024-06-09T05:54:47+0700] [ALPM-SCRIPTLET] Check GRUB_DISABLE_OS_PROBER documentation entry.
294601 [2024-06-09T05:54:47+0700] [ALPM-SCRIPTLET] Adding boot menu entry for UEFI Firmware Settings ...
294602 [2024-06-09T05:54:47+0700] [ALPM-SCRIPTLET] Detecting snapshots ...
294603 [2024-06-09T05:54:49+0700] [ALPM-SCRIPTLET] Found 50 snapshot(s)
294604 [2024-06-09T05:54:49+0700] [ALPM-SCRIPTLET] Unmount /tmp/grub-btrfs.M0f4cSCrjx .. Success
294605 [2024-06-09T05:54:49+0700] [ALPM-SCRIPTLET] done
294606 [2024-06-09T05:54:49+0700] [ALPM] running 'zzz-prevent-interruption-post.hook'...
294607 [2024-06-09T05:54:49+0700] [ALPM-SCRIPTLET] Removed "/run/systemd/system/halt.target".
294608 [2024-06-09T05:54:49+0700] [ALPM-SCRIPTLET] Removed "/run/systemd/system/poweroff.target".
294609 [2024-06-09T05:54:49+0700] [ALPM-SCRIPTLET] Removed "/run/systemd/system/reboot.target".
294610 [2024-06-09T05:54:49+0700] [ALPM-SCRIPTLET] Removed "/run/systemd/system/kexec.target".
294611 [2024-06-09T05:54:49+0700] [ALPM-SCRIPTLET] Removed "/run/systemd/system/suspend.target".
294612 [2024-06-09T05:54:49+0700] [ALPM-SCRIPTLET] Removed "/run/systemd/system/hibernate.target".
294613 [2024-06-09T05:54:49+0700] [ALPM-SCRIPTLET] Removed "/run/systemd/system/hybrid-sleep.target".
294614 [2024-06-09T05:54:49+0700] [ALPM-SCRIPTLET] Removed "/run/systemd/system/suspend-then-hibernate.target".
294615 [2024-06-09T05:54:49+0700] [ALPM-SCRIPTLET] Removed "/run/systemd/system/sleep.target".
294616 [2024-06-10T21:48:45+0700] [PACMAN] Running '/usr/bin/pacman --sync --refresh'
````

```zz-snap-pac-post.hook``` was executed before ```zz_snap-pac-grub-post.hook```

**Comment by max-baz** [comment]
Thanks! I'm tempted to name our hook `zz-snap-pac-postz-grub.hook`, to be super sure it goes after snap-pac-post.hook, and stays close to it. @leonkacowicz thoughts?

**Comment by ckotte** [comment]
Should work and should be executed after my custom ```zz-snap-pac-postz-config-sys.hook``` hook

Edit: Shouldn't it be ```zz-snap-pac-postz-grub.hook```???

**Comment by max-baz** [comment]
Thanks, of course 😁Edited

**Comment by leonkacowicz** [comment]
> Thanks! I'm tempted to name our hook `snap-pac-postz-grub.hook`, to be super sure it goes after snap-pac-post.hook, and stays close to it. @leonkacowicz thoughts?

The file names were supposed to start with a number so that each file maintainer could enforce the order using the number, but my hooks dir is full of files that violate that, so it's a mess already, so I don't mind whatever name that keeps the order.

Edit: these files are from other packages (nothing to do with this one)

**Comment by leonkacowicz** [comment]
@maximbaz @ckotte I updated the file name to match the suggestion.

**Review by max-baz — APPROVED** [review]

**Comment by max-baz** [comment]
Thanks to both of you, release is cut and AUR pkg is updated :pray:

**Pull request merged**
